apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    project: cicd
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.target-port }}
